language: generic
deploy:
  provider: s3
  access_key_id: AKIAI7FVPLJBUEWDKRLQ
  secret_access_key: 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
  bucket: vinnik
  on:
    repo: glushik/lab3
  acl: public_read
